apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: dev
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: yw24251436/product-service:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: product-service-config
            - secretRef:
                name: product-service-secret